use crate::run_validation::GovernorValidity;
use crate::workflow::WorkflowCollectPlanStep;

const PRESSURE_DURATION: &str = "5s";
const PRESSURE_WORKERS: &str = "1";
const THERMAL_ABORT_C: &str = "75";
const NETWORK_BYTES: &str = "1048576";

pub(crate) fn pressure_composite_characterization_steps(
    target: &str,
    run_dir: &str,
    network_endpoint: Option<&str>,
) -> Vec<WorkflowCollectPlanStep> {
    let mut steps = vec![
        pressure_step(
            "pressure_latency_jitter",
            target,
            run_dir,
            "latency_jitter",
            Vec::new(),
            "pressure_jitter_is_boundary_probe_not_realtime_safe",
            "Run bounded latency/jitter pressure evidence; real-time claims still require operating-contract rules.",
            vec![
                "latency_jitter pressure may be measured, measured_partial, insufficient, refused, not_applicable, or contaminated".to_string(),
                "jitter evidence is a bounded pressure probe, not a production real-time guarantee".to_string(),
            ],
        ),
        pressure_step(
            "pressure_observer_pressure",
            target,
            run_dir,
            "observer_pressure",
            Vec::new(),
            "observer_pressure_bounded_not_observer_zero_cost",
            "Run observer pressure evidence so instrumentation overhead remains explicit.",
            vec![
                "observer pressure records measurement overhead; passive observation alone is context".to_string(),
                "observer pressure does not prove zero observer effect".to_string(),
            ],
        ),
        pressure_step(
            "pressure_memory_pressure",
            target,
            run_dir,
            "memory_pressure",
            Vec::new(),
            "memory_pressure_effect_required_for_coupling_claims",
            "Run bounded memory pressure evidence.",
            vec![
                "memory pressure must observe an effect before memory-related operating-contract claims can advance".to_string(),
            ],
        ),
        pressure_step(
            "pressure_storage_io",
            target,
            run_dir,
            "storage_io",
            Vec::new(),
            "storage_io_bounded_probe_required",
            "Run bounded storage I/O pressure evidence with cleanup verification.",
            vec![
                "storage I/O pressure is bounded and cleanup-aware; default write suitability remains conservative".to_string(),
            ],
        ),
        pressure_step(
            "pressure_cpu_pressure",
            target,
            run_dir,
            "cpu_pressure",
            vec!["--abort-temp-c", THERMAL_ABORT_C],
            "cpu_pressure_bounded_by_duration_workers_and_thermal_abort",
            "Run bounded CPU pressure evidence.",
            vec![
                format!(
                    "duration={PRESSURE_DURATION}; workers={PRESSURE_WORKERS}; abort_temp_c={THERMAL_ABORT_C}C"
                ),
                "CPU pressure is bounded and does not replace the CPU ladder or sustained-load steps".to_string(),
            ],
        ),
        pressure_step(
            "pressure_thermal_pressure",
            target,
            run_dir,
            "thermal_pressure",
            vec!["--abort-temp-c", THERMAL_ABORT_C],
            "thermal_pressure_not_24h_safety",
            "Run bounded thermal pressure evidence.",
            vec![
                format!(
                    "duration={PRESSURE_DURATION}; workers={PRESSURE_WORKERS}; abort_temp_c={THERMAL_ABORT_C}C"
                ),
                "thermal pressure is bounded evidence and does not support 24h sustained safety".to_string(),
            ],
        ),
        pressure_step(
            "pressure_network_counter_only",
            target,
            run_dir,
            "network_io",
            Vec::new(),
            "network_counter_only_not_bounded_transfer",
            "Record counter-only network evidence; endpoint-backed transfer is a separate step when configured.",
            vec![
                "counter-only network_io is not endpoint-backed transfer evidence".to_string(),
                "operating network boundary claims require network_mode=bounded_transfer and generated bytes".to_string(),
            ],
        ),
    ];

    if let Some(endpoint) = network_endpoint {
        steps.push(pressure_step(
            "pressure_network_endpoint_backed",
            target,
            run_dir,
            "network_io",
            vec!["--network-endpoint", endpoint, "--network-bytes", NETWORK_BYTES],
            "endpoint_backed_bounded_transfer_required_for_network_claims",
            "Run endpoint-backed bounded network transfer evidence against the configured receiver.",
            vec![
                format!("network_endpoint={endpoint}; network_bytes={NETWORK_BYTES}"),
                "endpoint-backed network evidence remains insufficient unless the bounded transfer completes".to_string(),
                "LAN topology and receiver behavior remain confounders".to_string(),
            ],
        ));
    }

    steps.push(composite_step(
        "composite_memory_storage_jitter",
        target,
        run_dir,
        "memory_storage_jitter",
        "memory_storage_jitter_requires_measured_composite",
        "Run the phased memory/storage/jitter composite probe.",
        vec![
            "composite coupling claims remain blocked unless this composite artifact is measured"
                .to_string(),
            "pressure artifact presence alone is not coupling evidence".to_string(),
        ],
    ));

    steps
}

#[allow(clippy::too_many_arguments)]
fn pressure_step(
    step_id: &str,
    target: &str,
    run_dir: &str,
    kind: &str,
    extra_args: Vec<&str>,
    claim_gate: &str,
    human_summary: &str,
    mut validation_after_step: Vec<String>,
) -> WorkflowCollectPlanStep {
    validation_after_step.insert(
        0,
        format!("pressure_kind={kind}; duration={PRESSURE_DURATION}; workers={PRESSURE_WORKERS}"),
    );
    let mut command_argv = vec![
        "adc-lab".to_string(),
        "pressure".to_string(),
        "run".to_string(),
        "--target".to_string(),
        target.to_string(),
        "--kind".to_string(),
        kind.to_string(),
        "--duration".to_string(),
        PRESSURE_DURATION.to_string(),
        "--workers".to_string(),
        PRESSURE_WORKERS.to_string(),
    ];
    command_argv.extend(extra_args.into_iter().map(str::to_string));
    command_argv.extend([
        "--run-dir".to_string(),
        run_dir.to_string(),
        "--json".to_string(),
    ]);
    step(
        step_id,
        "pressure",
        command_argv,
        vec!["pressure"],
        vec![format!("{run_dir}/pressure/{kind}.*.v2.json")],
        claim_gate,
        vec![
            GovernorValidity::Measured,
            GovernorValidity::MeasuredPartial,
            GovernorValidity::Insufficient,
            GovernorValidity::NotApplicable,
        ],
        vec![GovernorValidity::Refused, GovernorValidity::Contaminated],
        validation_after_step,
        human_summary,
    )
}

#[allow(clippy::too_many_arguments)]
fn composite_step(
    step_id: &str,
    target: &str,
    run_dir: &str,
    scenario: &str,
    claim_gate: &str,
    human_summary: &str,
    validation_after_step: Vec<String>,
) -> WorkflowCollectPlanStep {
    step(
        step_id,
        "pressure",
        vec![
            "adc-lab".to_string(),
            "pressure".to_string(),
            "composite".to_string(),
            "--target".to_string(),
            target.to_string(),
            "--scenario".to_string(),
            scenario.to_string(),
            "--duration".to_string(),
            PRESSURE_DURATION.to_string(),
            "--workers".to_string(),
            PRESSURE_WORKERS.to_string(),
            "--run-dir".to_string(),
            run_dir.to_string(),
            "--json".to_string(),
        ],
        vec!["composite"],
        vec![format!("{run_dir}/composite/{scenario}.*.v2.json")],
        claim_gate,
        vec![
            GovernorValidity::Measured,
            GovernorValidity::MeasuredPartial,
            GovernorValidity::Insufficient,
            GovernorValidity::NotApplicable,
        ],
        vec![GovernorValidity::Refused, GovernorValidity::Contaminated],
        validation_after_step,
        human_summary,
    )
}

#[allow(clippy::too_many_arguments)]
fn step(
    step_id: &str,
    phase: &str,
    command_argv: Vec<String>,
    expected_artifact_kinds: Vec<&str>,
    expected_artifact_paths_or_globs: Vec<String>,
    claim_gate: &str,
    continue_on: Vec<GovernorValidity>,
    stop_on: Vec<GovernorValidity>,
    validation_after_step: Vec<String>,
    human_summary: &str,
) -> WorkflowCollectPlanStep {
    WorkflowCollectPlanStep {
        step_id: step_id.to_string(),
        phase: phase.to_string(),
        command_argv,
        working_directory_policy: "repository_root".to_string(),
        execution_location: "controller".to_string(),
        requires_target_local: false,
        requires_controller: true,
        requires_approval_policy: false,
        requires_privileged_helper: false,
        expected_artifact_kinds: expected_artifact_kinds
            .into_iter()
            .map(str::to_string)
            .collect(),
        expected_artifact_paths_or_globs,
        claim_gate: claim_gate.to_string(),
        continue_on,
        stop_on,
        validation_after_step,
        human_summary: human_summary.to_string(),
    }
}
